# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del grupo musical', max_length=150)),
                ('web', models.URLField(blank=True, default='')),
                ('bio', models.TextField(help_text='Biograf\xeda del grupo')),
            ],
        ),
    ]
